model:  # model configuration
  input_size: 75  # input data size
  hidden_size: 512  # size of lstm hidden-layer
  embedding_input_size: 64  # output size of embedding layer
  model_name: ""  # name of the model/experiment

train:  # training phase
  learning_rate: 0.0005
  junk_size: 20
  junk_step: 5
  batch_size: 1
  save_step: 10  # save model every Nth epoch
  evaluation_step: 5  # run evaluation every Nth epoch
  report_step: 500  # print training report every Nth iteration

evaluation:  # evaluation phase
  threshold_steps: 10  # number of thresholds to generate, between 0-1
  report_step: 25  # print evaluation report every Nth iteration
  frame_size: 1  # number of frames to classify in detection evaluation
